application: vagamap
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /scripts
  static_dir: scripts

- url: /temp
  static_dir: temp
  
- url: /provider/edit
  script: vagamap.pages.provider.provider_edit
  
- url: /provider/list
  script: vagamap.pages.provider.provider_list
  
- url: /place/list
  script: vagamap.pages.place.place_list
  
- url: /handlers/testcode
  script: vagamap.handlers.testcode.handler


libraries:
- name: jinja2
  version: latest
  
- name: lxml
  version: latest
