application: vagamap
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /scripts
  static_dir: scripts

- url: /provider/edit
  script: vagamap.pages.provider.edit
  
- url: /provider/list
  script: vagamap.pages.provider.list
  
- url: /handlers/testcode
  script: vagamap.handlers.testcode.handler


libraries:
- name: jinja2
  version: latest
